In [1]:
from google_play_scraper import app

import pandas as pd

import numpy as np

In [2]:
#Scrape desired number of reviews
#Run kode ini jika ingin scrape data dengan jumlah tertentu. Ganti (misal, ingin scrape sejumlah 1000, maka ganti kode , count = 1000 )

from google_play_scraper import Sort, reviews

result, continuation_token = reviews(
    'com.telkom.tracencare',
    lang='id', # defaults to 'en'
    country='id', # defaults to 'us'
    sort=Sort.NEWEST, # defaults to Sort.MOST_RELEVANT you can use Sort.NEWEST to get newst reviews
    count=2500, # defaults to 100
    filter_score_with=None # defaults to None(means all score) Use 1 or 2 or 3 or 4 or 5 to select certain score
)

In [3]:
df_data = pd.DataFrame(np.array(result),columns=['review'])

df_data = df_data.join(pd.DataFrame(df_data.pop('review').tolist()))

df_data.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt
0,0c6299e1-0430-4bd7-a962-04425b3552db,Achmad Faisal,https://play-lh.googleusercontent.com/a-/AFdZu...,Sudah vaksin tapi sertifikat belom keluar suda...,1,0,4.5.1,2022-08-14 12:09:13,None,NaT
1,e288dedc-bea3-4de1-b1dd-bbac32ba1225,Stineke Mare,https://play-lh.googleusercontent.com/a-/AFdZu...,Min kok ngak bisa ke buka sertifika nya,2,0,4.5.1,2022-08-14 11:26:51,"Halo Stineke Mare,\n\nMohon maaf atas ketidakn...",2021-11-23 13:25:55
2,4d7aea6d-6f9f-48bd-b9a3-94962d886f64,AHMAD YANI,https://play-lh.googleusercontent.com/a/AItbvm...,Terlalu rumit sungguh kecewa Udah di masukin d...,2,0,4.5.0,2022-08-14 10:35:37,None,NaT
3,cc7ea376-b979-4174-be0e-6c5b986e828f,Hendrik Timisela,https://play-lh.googleusercontent.com/a/AItbvm...,Aplikasi ini sangat bermanfaat.....,5,0,4.4.8,2022-08-14 10:34:40,None,NaT
4,f2fd3a83-182f-42b5-b023-d5bf21919c6b,Heni Susanti,https://play-lh.googleusercontent.com/a-/AFdZu...,Ok bgt,5,0,4.5.1,2022-08-14 10:21:21,None,NaT

In [4]:
len(df_data.index) #count the number of data we got

2500

In [5]:
df_data[['userName', 'score','at', 'content']].head()  #preview userName, rating, date-time, and reviews only

,userName,score,at,content
0,Achmad Faisal,1,2022-08-14 12:09:13,Sudah vaksin tapi sertifikat belom keluar suda...
1,Stineke Mare,2,2022-08-14 11:26:51,Min kok ngak bisa ke buka sertifika nya
2,AHMAD YANI,2,2022-08-14 10:35:37,Terlalu rumit sungguh kecewa Udah di masukin d...
3,Hendrik Timisela,5,2022-08-14 10:34:40,Aplikasi ini sangat bermanfaat.....
4,Heni Susanti,5,2022-08-14 10:21:21,Ok bgt

In [6]:
#Run This Code to Sort the Data By Date 

new_df = df_data[['userName', 'score','at', 'content']]
sorted_df = new_df.sort_values(by='at', ascending=False) #Sort by Newst, change to True if you want to sort by Oldest.
sorted_df.head()

,userName,score,at,content
0,Achmad Faisal,1,2022-08-14 12:09:13,Sudah vaksin tapi sertifikat belom keluar suda...
1,Stineke Mare,2,2022-08-14 11:26:51,Min kok ngak bisa ke buka sertifika nya
2,AHMAD YANI,2,2022-08-14 10:35:37,Terlalu rumit sungguh kecewa Udah di masukin d...
3,Hendrik Timisela,5,2022-08-14 10:34:40,Aplikasi ini sangat bermanfaat.....
4,Heni Susanti,5,2022-08-14 10:21:21,Ok bgt

In [7]:
my_df = sorted_df[['userName', 'score','at', 'content']] #get userName, rating, date-time, and reviews only

In [8]:
my_df

,userName,score,at,content
0,Achmad Faisal,1,2022-08-14 12:09:13,Sudah vaksin tapi sertifikat belom keluar suda...
1,Stineke Mare,2,2022-08-14 11:26:51,Min kok ngak bisa ke buka sertifika nya
2,AHMAD YANI,2,2022-08-14 10:35:37,Terlalu rumit sungguh kecewa Udah di masukin d...
3,Hendrik Timisela,5,2022-08-14 10:34:40,Aplikasi ini sangat bermanfaat.....
4,Heni Susanti,5,2022-08-14 10:21:21,Ok bgt
...,...,...,...,...
2495,Sarah Oasis,1,2022-07-26 14:09:16,susah dan sangat sangat sangat merepotkan. mau...
2496,Edy sudrajat,5,2022-07-26 14:02:47,Jos
2497,diah agus tiyani,1,2022-07-26 14:00:07,Sudah vaksin ke 3 tp di app tidak mincul serti...
2498,Oscar Imanuel,5,2022-07-26 13:57:11,Apknya bagus bangettt
2499,Danewi Bae,5,2022-07-26 13:55:39,Cepat Aplikasinya

In [9]:
my_df.to_excel("scrapped_data_google play.xlsx", index = False)